SitDeSextaReloaded/urls.py
from django.conf.urls import patterns, include, url

from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'SitDeSextaReloaded.views.home', name='home'),
    # url(r'^SitDeSextaReloaded/', include('SitDeSextaReloaded.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^admin/', include(admin.site.urls)),

    #    comments module
    url(r'^comments/', include('django.contrib.comments.urls')),

    #My Urls
    url(r'^$', 'Ranking.views.landing_page'),
    url(r'^index/$','Ranking.views.index'),
    url(r'^contato','Ranking.views.contato'),

    (r'^static/media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),

    url(r'^tournaments/(?P<tournament_id>\d+)$' , 'Ranking.views.tournament'),
    url(r'^tournaments', 'Ranking.views.tournaments'),

    url(r'^news/(?P<news_id>\d+)$', 'Ranking.views.news'),
    (r'^accounts/', include('userena.urls')),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT}))

Ranking/models.py
__author__ = 'AkiO'
# -*- coding: UTF-8 -*-

from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.db.models.signals import post_save
from userena.models import UserenaBaseProfile
from django.utils.translation import ugettext as _

class Player(UserenaBaseProfile):
    '''
        Jogador de porker que participa de torneio
        relacionamento com ITM de 1 pra N
        relacionamento N pra N com torneio
    '''
    user = models.OneToOneField(User,
        unique=True,
        verbose_name=_('user'),
        related_name='my_profile',
        blank=True,
        null=True,
    )

    nickname = models.CharField(max_length=30)
    description = models.TextField(blank=True)

    def __unicode__(self):
        return self.user.username

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Player.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)

class Tournament(models.Model):
    '''
        Torneio evento de poker
        Relacionamento n pra n com player
        Relacionamento 1 pra n com itm

    '''
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=250)
    logo = models.ImageField(upload_to="tournament_logos",blank=True,null=True)

    buy_in = models.FloatField()
    qty_chips_buy_in = models.IntegerField()
    rebuy = models.FloatField()
    qty_chips_rebuy = models.IntegerField()
    add_on = models.FloatField()
    qty_chips_add_on = models.IntegerField()

    player = models.ManyToManyField(Player,related_name='player_tournaments')
    location = models.CharField(max_length=30)
    start_at = models.DateTimeField()
    total_avaliable_points = models.IntegerField(blank=True, null=True)
    total_money = models.FloatField(blank=True,null=True)
    total_buy_in = models.IntegerField()
    total_rebuy = models.IntegerField()
    total_add_on = models.IntegerField()

    def updateTotalMoney(self):
        #Calcula o total de dinheiro no prize pool
        self.total_money = (self.buy_in * self.total_buy_in)\
                           + (self.add_on * self.total_add_on)\
                           + (self.rebuy * self.total_rebuy)

        super(Tournament,self).save()

    def updateAvaliablePoints(self):
        self.total_avaliable_points = len(self.player.all())

        super(Tournament,self).save()

    def save(self, force_insert=False, force_update=False, using=None):
        #Salvo o objeto torneio
        super(Tournament,self).save()

        self.updateTotalMoney()
        self.updateAvaliablePoints()

    def __unicode__(self):
        return self.name

class Itm(models.Model):
    '''
        premiação de cada torneio
        relacionamento 1 para n com torneio
        e relacionamento 1 para n com jogador
    '''
    position = models.IntegerField()
    percent = models.FloatField()
    final_value = models.FloatField(blank=True)
    tournament = models.ForeignKey(Tournament)
    player = models.ForeignKey(Player)

    #Calcula o valor do itm
    def save(self, force_insert=False, force_update=False, using=None):
        self.final_value = self.tournament.total_money * (self.percent / 100)

        super(Itm,self).save()

    def __unicode__(self):
        return self.tournament.name + '-' + self.player.nickname

class News(models.Model):
    '''
        Noticias exibidas na home
    '''

    title = models.CharField(max_length=250)
    shortContent = models.CharField(max_length=160)
    content = models.TextField()
    photo = models.ImageField(upload_to='NewsPhoto')
    pub_date = models.DateTimeField(default=datetime.now , blank=True)
    user = models.ForeignKey(Player)
    like = models.IntegerField(blank=True,null=True)

    def __unicode__(self):
        return self.title

class League(models.Model):
    title = models.CharField(max_length=60)
    description = models.CharField(max_length=500)

    tournament = models.ForeignKey(Tournament)

SitDeSextaReloaded/templates/base.html
<!DOCTYPE html>
{% load i18n static %}
<html lang="en">
<head>
    <meta charset="utf-8">

    <title>{% block title %}Sit de Sexta! - Home APLHA{% endblock %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="AKIO SK">

    <!-- Le styles -->
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/master.css"/>
    <link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
        body {
            padding-top: 60px;
            padding-bottom: 40px;
        }
        .sidebar-nav {
            padding: 9px 0;
        }
    </style>
    <link href="{{ STATIC_URL }}css/bootstrap-responsive.css" rel="stylesheet">
    <link rel="javascript" href="{{ STATIC_URL }}js/jquery.js">
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="{{ STATIC_URL }}img/logo.png">

    {% block extra_css %}
    {% endblock %}

    {% block extra_js %}
    {% endblock %}
</head>

<body class="">
{% load thumbnail %}
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="#">Sit de Sexta!</a>
            <div class="btn-group pull-right">
                {% if user.is_authenticated %}
                    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="icon-user"></i> {{ user.username }}
                    <span class="caret"></span>
                    </a>

                    <ul class="dropdown-menu">
                        <li><a href="{% url userena_profile_detail user.username %}">Profile</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url userena_signout %}"><span> Sair </span></a></li>
                    </ul>
                {% else %}
                    <a class="btn dropdown-toggle" data-toggle="dropdown" href="{% url userena_signin %}">
                        <i class="icon-user"></i> Login
                        <span class="caret"></span>
                    </a>
                {% endif %}
            </div>
            <div class="nav-collapse">
                <ul class="nav">
                    <li class="active"><a href="/"><i class="icon-home"></i> Home </a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url userena_profile_detail user.username %}"><i class="icon-star"></i> Profile </a></li>
                    {% endif %}
                    <li><a href="/tournaments"><i class="icon-screenshot"></i> Tournaments </a></li>
                    <li><a href="/about"><i class="icon-th"></i> About </a></li>
                    <li><a href="/contato"><i class="icon-pencil"></i> Contact </a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row-fluid">

            {% block content %}

            {% endblock %}

    </div>

    <hr>

    <footer>
        <p>&copy; Sit de Sexta Alpha 2012 - Help Us</p>
    </footer>

</div><!--/.fluid-container-->

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{{ STATIC_URL }}js/jquery.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-transition.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-alert.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-modal.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-dropdown.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-scrollspy.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-tab.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-tooltip.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-popover.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-button.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-collapse.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-carousel.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-typeahead.js"></script>

</body>
</html>

SitDeSextaReloaded/templates/contact.html
{% extends "base.html" %}

{% block Title %}
    Sit de Sexta! - Contato (ALPHA)
{% endblock %}

{% load thumbnail %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/contato.css"/>
{% endblock %}

{% block extra_js %}

{% endblock %}

{% block content %}

    {% if mostrar %}<h3>{{ mostrar }}</h3>{% endif %}

    <h1>Informe seus dados abaixo:</h1>
    <hr>
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form }}

            <tr>
                <th>&nbsp;</th>
                <td><input class="btn btn-info" type="submit" value="Enviar contato"/></td>
            </tr>
        </table>
    </form>

{% endblock %}


SitDeSextaReloaded/templates/index.html
{% extends "base.html" %}

{% load i18n %}
{% block title %}{% blocktrans with profile.user.username as username %}Bem vindo! {{ username }}.{% endblocktrans %}{% endblock %}

{% load thumbnail %}

{% block extra_css %}

{% endblock %}

{% block extra_js %}

{% endblock %}

{% block content %}

    {% csrf_token %}
{#    <div class="span3">#}
{#        <div class="well box" >#}
{#            <img class="mugshot" src="{{ profile.get_mugshot_url }}" alt="{% trans "Your mugshot" %}" />#}
{##}
{#            {% if profile.nickname %}#}
{#                <dt>{% trans "nickname" %}</dt>#}
{#                <dd>{{ profile.nickname }}</dd>#}
{#            {% endif %}#}
{##}
{#            <hr>#}
{#            <dl>#}
{#                {% if profile.user.get_full_name %}#}
{#                    <dt>{% trans "Name" %}</dt>#}
{#                    <dd>{{ profile.user.get_full_name }}</dd>#}
{#                {% endif %}#}
{#                {% if profile.user.email and not hide_email %}#}
{#                    <dt>{% trans "Email" %}</dt>#}
{#                    <dd>{{ profile.user.email }}</dd>#}
{#                {% endif %}#}
{#            </dl>#}
{#        </div>#}
{#    </div>#}

    <div class="span11">
        <div class="hero-unit box">
            <h1>Você Está no index autenticado</h1>
            <p>Aqui no sit de sexta você acompanha tudo que está acontecendo nos torneios ao seu redor, chame seu amigo e organize aquele
            torneio semanal, poste e discuta aquela Bad Beat na mesa final e poste tudo nas redes sociais para todos ficarem sabendo!</p>
            <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>
        </div>

        <div class="row-fluid">
            <h1>TODO: Listagem com os ultimos torneios que o usuario participou</h1>
            {% for tournament in tournaments %}
                <h3>{{ tournament.name }}</h3>
            {% endfor %}
        </div>
    </div>

{% endblock %}


SitDeSextaReloaded/templates/landing_page.html
{% extends "base.html" %}

{% block Title %}
    Sit de Sexta! - Home (ALPHA)
{% endblock %}

{% load thumbnail %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/master.css"/>
{% endblock %}

{% block extra_js %}

{% endblock %}

{% block content %}

    {% csrf_token %}


    <div class="hero-unit">
        <h1>Não perca a ação!</h1>
        <p>Aqui no sit de sexta você acompanha tudo que está acontecendo nos torneios ao seu redor, chame seu amigo e organize aquele
            torneio semanal, poste e discuta aquela Bad Beat na mesa final e poste tudo nas redes sociais para todos ficarem sabendo!</p>
        <p><a class="btn btn-primary btn-large" href="{% url userena_signup %}">Cadastre-Se Agora! &raquo;</a></p>
    </div>


    <div class="row-fluid">
        {% for new in news %}
            <div class="span4">
                <h2>{{ new.title }}</h2>
                <p>{{ new.content }} </p>
                <p><a class="btn" href="/news/{{ new.id }}">View details &raquo;</a></p>
            </div>
        {% endfor %}
    </div>

{% endblock %}


SitDeSextaReloaded/templates/news.html
{% extends "base.html" %}

{% block Title %}
    Sit de Sexta! - {{ new.title }}
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/news.css"/>
{% endblock %}

{% block extra_js %}

{% endblock %}

{% block content %}

    {% load thumbnail %}

    <div class="span12">
        <h1>{{ new.title }}</h1>

        <h6>{{ new.user.name }} - {{ new.pub_date }}</h6>
        <hr>
        <div class="">
            <ul class="thumbnails">
                <li class="" style="margin: 0 auto;">
                    <a href="#" class="thumbnail" >
                        <img src="{{ new.photo.url }}" alt="">
                    </a>
                </li>
            </ul>
        </div>
            <p>{{ new.content }}</p>
    </div>


{% endblock %}

SitDeSextaReloaded/templates/tournament.html
{% extends "base.html" %}

{% block Title %}
    Sit de Sexta! - {{ tournament.name }} (ALPHA)
{% endblock %}

{% load thumbnail %}

{% block extra_css %}{% endblock %}

{% block extra_js %}{% endblock %}

{% load comments %}

{% block content %}

    <div class="span12">

        <h1>{{ tournament.name }}</h1>
        <hr>
        <div class="">
            {% if tournament.logo %}
                <ul class="thumbnails">
                    <li>
                        <a href="#" class="thumbnail" >
                            <img src="{{ tournament.logo|thumbnail_url:'tournament_logo' }}">
                        </a>
                    </li>
                </ul>
            {% endif %}
            <p>{{ tournament.description }}</p>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <h4>Estrutura</h4>
                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <td>buy_in: </td>
                            <td>$ {{ tournament.buy_in }}</td>
                        </tr>
                        <tr>
                            <td>qty_chips_buy_in: </td>
                            <td>{{ tournament.qty_chips_buy_in }}</td>
                        </tr>
                        <tr>
                            <td>rebuy: </td>
                            <td>$ {{ tournament.rebuy }}</td>
                        </tr>
                        <tr>
                            <td>qty_chips_rebuy: </td>
                            <td>{{ tournament.qty_chips_rebuy }}</td>
                        </tr>
                        <tr>
                            <td>add_on: </td>
                            <td>$ {{ tournament.add_on }}</td>
                        </tr>
                        <tr>
                            <td>add_on: </td>
                            <td>{{ tournament.qty_chips_add_on }}</td>
                        </tr>
                        <tr>
                            <td>location: </td>
                            <td>{{ tournament.location }}</td>
                        </tr>
                        <tr>
                            <td>start_at: </td>
                            <td>{{ tournament.start_at }}</td>
                        </tr>
                        <tr>
                            <td>total_avaliable_points</td>
                            <td>{{ tournament.total_avaliable_points }}</td>
                        </tr>
                        <tr>
                            <td>total_money</td>
                            <td>$ {{ tournament.total_money }}</td>
                        </tr>
                        <tr>
                            <td>total_buy_in</td>
                            <td>{{ tournament.total_buy_in }}</td>
                        </tr>
                        <tr>
                            <td>total_rebuy</td>
                            <td>{{ tournament.total_rebuy }}</td>
                        </tr>
                        <tr>
                            <td>total_add_on</td>
                            <td>{{ tournament.total_add_on }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="span6">
                <h4>Premiação</h4>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Position</th>
                            <th>Player Name</th>
                            <th>Money</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for itm_player in tournament.itm_set.all %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ itm_player.player.user }} {% if itm_player.player.nickname %}- ({{ itm_player.player.nickname }}){% endif %}</td>
                                <td>$ {{ itm_player.final_value }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>

                </table>
            </div>
        </div>

        <div>
            <div class="span3">
                <h3>Envie um comentario</h3>
                <hr>
                {% render_comment_form for tournament %}
            </div>
            <div class="span8">
                <h3>Comentarios</h3>
                <hr>
                {% get_comment_list for tournament as comentarios %}
                {% for comentario in comentarios %}
                <div>
                    Nome: {{ comentario.name }}
                    {% if comentario.url %}URL: {{ comentario.url }}{% endif %}<br />
                    {{ comentario.comment|linebreaks }}
                </div>
                {% endfor %}
            </div>
        </div>

    </div>

{% endblock %}

SitDeSextaReloaded/templates/tournaments.html
{% extends "base.html" %}

{% block Title %}
    Sit de Sexta! - Tournaments (ALPHA)
{% endblock %}

{% load thumbnail %}

{% block extra_css %}{% endblock %}

{% block extra_js %}{% endblock %}

{% block content %}
    <h1>Não perca os ultimos torneios</h1>

    <hr>

    {% for tournament in tournaments %}
        <div class="span9">
            <h2>{{ tournament.name }}</h2>
            <p>{{ tournament.description }}</p>

            <div class="span3">
                <h4>Details</h4>
                <p>Buy-In: R$ {{ tournament.buy_in }} </p>
                <p>Re-Buy: R$ {{ tournament.rebuy }} </p>
                <p>Add-On: R$ {{ tournament.add_on }} </p>
            </div>

            <div class="span3">
                <h4>Prize Pool</h4>
                <ul>
                    {% for itm in tournament.itm_set.all %}
                        <li>{{ itm.position }} - R$ {{ itm.final_value }} - {{ itm.player }}</li>
                    {% endfor %}
                </ul>
            </div>


        </div>
        <div class="span3">
            <p><a class="btn btn-info " href="/tournaments/{{ tournament.pk }}"><i class="icon-share"></i> See More</a></p>
        </div>
    {% endfor %}
{% endblock %}